### PR TITLE
Fix parser bugs

### LINKED ISSUE #187: [PE-D] Wrong exception message generated
As I keyed in "edit u/ 2/",

it says i have keyyed in the wrong item number.

However, the fault here is wrong input format which does not match the error mesage.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ruyian/ped#6

### LINKED ISSUE #198: [PE-D] Potential bug 3: Update of  height, weight
As shown below, the height in the user profile is updated even though the input height is invalid/meaningless, i.e, Not a possible input of a height. Maybe it would be better to prompt an error message in this case to disable such input.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KairuiHu/ped#3

### LINKED ISSUE #199: [PE-D] Potential bug 4: Update of gender with invalid input
As shown below, the gender can be updated even though the input is invalid/meaningless, i.e., Not a possible value of gender (with respect to your user guide). In fact, I guess that any input strings containing m/f are allowed in your implementation. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KairuiHu/ped#4

### LINKED ISSUE #202: [PE-D] Invalid input separated by a white space is accepted by the program
The program is not affected when invalid input is given when it is separated by a white space

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dyahnafisah/ped#4

### LINKED ISSUE #207: [PE-D] Suggestion for the displayed output for the exception
I think it's better to say "Please input goal as an integer" rather than just "a number" since decimal is also a number.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: dyahnafisah/ped#5

### LINKED ISSUE #209: Allow deleting of multiple indexes for upcoming list
Parsing by @tlyi 
Functionality by @xingjie99

### LINKED ISSUE #211: Trim names of exercises/food when adding
image

### PR DESCRIPTION
**Pull request by tlyi**
- Refactor Parser and ParserUtil methods to reduce code duplication and long methods 
- Trim inputs so that whitespace do not affect (Fixes #211) (Fixes #187)
- Fix parsing bug for extra/unnecessary parameters (Fixes #202) (Fixes #199) (Fixes #198)
- Add parser support for deleting multiple indexes (for ebank, fbank, upcoming) (Fixes #209)
- Change error message from "number" to "whole number" to be clearer about it being integer (Fixes #207)
- Make it compulsory for item type to be first word in input after command word
- Make it compulsory for prefixes to be separated by whitespace

### CODE REVIEW

File: src/main/java/seedu/duke/logic/parser/ParserUtils.java [hunk 1]
```diff
@@ -22,410 +21,278 @@
...
-                logger.log(Level.WARNING, "Detected empty date input after prefix but date is required!");
-                throw new ParamMissingException(ParserMessages.MESSAGE_ERROR_NO_DATE);
-            } else {
-                logger.log(Level.WARNING, "Detected empty date input after prefix, assuming date to be now");
-                return LocalDate.now();
-            }
-        } catch (DateTimeParseException e) {
-            throw new ParamInvalidException(ParserMessages.MESSAGE_ERROR_INVALID_DATE_FORMAT);
+            throws ParserException {
+        LocalDate localDate = extractGeneralDate(params, Command.COMMAND_PREFIX_DATE);
```
Comment (tryyang2001) [inline src/main/java/seedu/duke/logic/parser/ParserUtils.java:221]: Just curious where is the implementation of the method `extractGeneralDate`, since I cannot find it :(

Comment (tlyi) [reply src/main/java/seedu/duke/logic/parser/ParserUtils.java:221]: It starts from line 85 of `ParserUtils`! :)

Comment (tryyang2001) [reply src/main/java/seedu/duke/logic/parser/ParserUtils.java:221]: Thank you! It looks good!

**Review by tryyang2001 — APPROVED** [review]
Thanks for refactoring the Parser, looks good to merge now :D
